gemini_api_key = "AIzaSyAwCav_u6_PcfkmIJU3RWGEayzE2AFG3Xg"

GEMINI_API_KEY = "AIzaSyAwCav_u6_PcfkmIJU3RWGEayzE2AFG3Xg"
GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent"

